### ISSUE TITLE
validate database tool struggles with multiple Feature Datasets

### ISSUE THREAD

**Issue by BenjiDa** [usgs/gems-tools-pro#21]
Running into an error when validating a database with multiple Feature Datasets.  See error message below...

```
Traceback (most recent call last):
  File "C:\Users\bmelosh\Documents\ArcGIS\Tools\gems-tools-pro-master\Scripts\GeMS_ValidateDatabase_AGP2.py", line 1044, in <module>
    dsc = arcpy.Describe(fc)
  File "C:\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1287, in Describe
    return gp.describe(value, data_type)
  File "C:\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 384, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
RuntimeError:  ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
```

**Comment by ethoms-usgs** [comment]
Could you post more of the messages? It would be good to see what else was being reported before the error. Screen grabs of the contents pane and the gdb from the catalog pane would be good too.

**Comment by BenjiDa** [comment]
Sure, it appears to be crashing when attempting to check `SeismicityMap for other stuff`,  SeismicityMap being the second Feature Dataset within the geodatabase. When I remove SeismicityMap from the geodatabase the tool works fine
![Screenshot 2022-04-28 105913](https://user-images.githubusercontent.com/18178879/165817733-74b1cd35-acc2-4ef5-9153-985f14071e9c.png)
.

**Comment by BenjiDa** [comment]
There are feature classes Seismicity and SeismicityCartographicLines.  Upon further inspection it appears to be failing due the feature class name 'Seismicity'. Not exactly sure what the issue is here, but it is easy enough to rename.  See error messages below
![Screenshot 2022-04-28 145221](https://user-images.githubusercontent.com/18178879/165859353-8c417a50-ddb3-4504-8ab3-b91a931213f7.png)
![Screenshot 2022-04-28 145327](https://user-images.githubusercontent.com/18178879/165859383-2937f5a4-f774-4cef-a638-74c3072ff1e8.png)
![Screenshot 2022-04-28 152607](https://user-images.githubusercontent.com/18178879/165859391-3f896117-c2b5-473d-a687-a58b3d52b232.png)

**Comment by ethoms-usgs** [comment]
The issue I am seeing is that Pro cannot open MicroSeismicity. It can't be added to a map and I can't browse the contents in ArcCatalog. Are you able to see and work with the features in there?
