### ISSUE TITLE
Topology check tool crashes

### ISSUE THREAD

**Issue by tfelger** [usgs/gems-tools-pro#5]
I tried the new version of the topology check tool, and it crashes, with the following error message:
 
Traceback (most recent call last):
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcPro\gems-tools-pro-master_20210305\Scripts\GeMS_TopologyCheck_AGP2.py", line 821, in <module>
    badNodes,faultFlipNodes,missingConcealedArcNodes,connectFIDs = processNodes(nodeList,hKeyDict)
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcPro\gems-tools-pro-master_20210305\Scripts\GeMS_TopologyCheck_AGP2.py", line 281, in processNodes
    if isFault(arcs[0].Type) and isFault(arcs[1].Type) and sameToFrom(arcs[0],arcs[1]):
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcPro\gems-tools-pro-master_20210305\Scripts\GeMS_utilityFunctions.py", line 137, in isFault
    if lType.upper().find('FAULT') > -1:
AttributeError: 'NoneType' object has no attribute 'upper'
 Failed to execute (TopologyCheck).

![image](https://user-images.githubusercontent.com/52179206/110148398-00fdca00-7d9a-11eb-8583-3ea6f9f22cdf.png)

**Comment by ethoms-usgs** [comment]
Sorry for the delay!
The error suggests that there is no Type value to check. Are all rows in ContactsAndFaults filled in with a Type?
